baseURL = "http://www.andrew-schneider.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Andrew Schneider"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    title = "Andrew Schneider"
    author = "andrew schneider"
    copyright = "2021-{{ YEAR }}"
    description = "Making, Tinkering, and Studying"
    profilePicture = "images/profile.jpg"
    keywords = ""
    favicon = "favicons/"
    # example ["css/custom.css"]
    customCss = []
    # example ["js/custom.js"]
    customJs = []
    mainSections = [] 
    images = ["images/site-feature-image.png"]
    doNotLoadAnimations = true
    # Form Spree Contact Form
    # contactFormAction = "https://formspree.io/f/your-form-hash-here"
    # Google Fonts
    # googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
    # Google Site Verify
    # googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    singleDateFormat = "2/1/2006"
    indexDateFormat = "2/1/2006"
    listDateFormat = "Jan, 2006"
    # Commento Comments
    # CommentoURL = "https://commento.example.com/js/commento.js"
    # Read More links for truncated summaries
    # readMore = true
    # postSectionName = "Archive"
    disableThemeSwitcher = true
    displayMode = 'nord-dark'
    contentratio = 0.7

    reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[simpleAnalytics]
    # enable = true
    # customurl = "https://analytics.example.com"

## Math settings
    [math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
    # use 'fab' when brand icons, use 'fas' when standard solid icons.
    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/andrew-schneider/"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/Andrew-Schneider"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:aschneiderb4@gmail.com"

## Menu items

[menu]
  [[menu.main]]
  name = "About Me"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  identifier = "Projects"
  name = "Projects"
  url = "/Projects/"
  weight = 400

  [[menu.main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

# Deployment
    [deployment]

    [[deployment.targets]]
    name = "andrew-schneider.com"
    URL = "s3://www.andrew-schneider.com?region=us-east-1"

    # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
    # cloudFrontDistributionID =	"<your cloud fornt ID>"

    [[deployment.matchers]]
    # Cache static assets for 20 years.
    pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
    cacheControl = "max-age=630720000, no-transform, public"
    gzip = true

    [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true