baseURL = "http://www.andrew-schneider.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Andrew Schneider"

# theme as hugo module
theme = "github.com/lxndrblz/anatole"
# theme as git submodule
# theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
    weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[params]
    title = "Andrew Schneider"
    author = "Andrew schneider"
    copyright = "2021-{{ YEAR }}"
    description = "Making, Tinkering, and Studying"
    profilePicture = "images/profile.jpg"
    keywords = ""
    favicon = "favicons/"
    # example ["css/custom.css"]
    customCss = []
    # example ["js/custom.js"]
    customJs = []
    mainSections = ["post"] 
    images = ["images/site-feature-image.png"]
    doNotLoadAnimations = true
    # Form Spree Contact Form
    #contactFormAction = "https://formspree.io/f/your-form-hash-here"
    #contactFormReCaptcha = "your-site-key-here"
    # Google Fonts
   #googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
    # Google Site Verify
    #googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    singleDateFormat = "1/2/2006"
    indexDateFormat = "1/2/2006"
    listDateFormat = "Jan, 2006"
    # Commento Comments
    # CommentoURL = "https://commento.example.com/js/commento.js"
    # Read More links for truncated summaries
    # readMore = true
    # postSectionName = "post"
    # relatedPosts = true
    # numberOfRelatedPosts = 3
    disableThemeSwitcher = false
    displayMode = 'lightmode'
    contentratio = 0.7

    reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true
[simpleAnalytics]
    # enable = true
    # customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
    [math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
    # use 'fab' when brand icons, use 'fas' when standard solid icons.
    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/andrew-schneider/"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/Andrew-Schneider"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:aschneiderb4@gmail.com"
    
[mermaid]
# enable = true

## Menu items

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  identifier = "About Me"
  name = "About"
  url = "/About/"
  weight = 200

  ## [[menu.main]]
  # name = "Portfolio"
  # weight = 300
  # identifier = "Portfolio"
  # url = "/portfolio/"

  [[menu.main]]
  identifier = "Archive"
  name = "Archive"
  url = "/post/"
  weight = 400

  [[menu.main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"

  [[menu.main]]
  name = "Awards"
  weight = 510
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[menu.main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[menu.main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

# Deployment
    [deployment]

    [[deployment.targets]]
    name = "andrew-schneider.com"
    URL = "s3://www.andrew-schneider.com?region=us-east-1"

    # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
    # cloudFrontDistributionID =	"<your cloud fornt ID>"

    [[deployment.matchers]]
    # Cache static assets for 20 years.
    pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
    cacheControl = "max-age=630720000, no-transform, public"
    gzip = true

    [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> /Users/andrewschneider/Documents/Git/andrew-schneider.com/themes"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false